numerics: main.cpp calculate.cpp define.cpp test.cpp integral.cpp gradient.cpp  main.h
	g++ -o numerics -std=gnu++11 -Wall -Werror -ggdb3 main.cpp calculate.cpp define.cpp test.cpp integral.cpp gradient.cpp

clean:
	rm -f *~ numerics
